services:
  db:
    image: postgres:17
    container_name: auth-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: .
    container_name: auth-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data:
